/*
    * mcal_ccp_cfg.h
    *
    *  Created on: 6/4/2024
*/

/* INCLUDS */


/* MACRO DECLARATIONS */

#define CPP_CFG_CAPTURE_MODE  0X00
#define CPP_CFG_COMPARE_MODE  0X01
#define CPP_CFG_PWM_MODE      0X02

#define CCP1_SELECTED_MODE (CPP_CFG_CAPTURE_MODE)
#define CCP2_SELECTED_MODE (CPP_CFG_CAPTURE_MODE)
/* MACRO FUNTIONS DECLARATIONS */

/* DATA TYPE DECLARATIONS (ENUMS,UNIONS,STRUCTS) */



/* FUNTIONS DECLARATIONS */