/* 
 * File:   mcal_interrupt_gen_cfg.h
 * Author: houda
 *
 * Created on February 26, 2024, 7:56 PM
 */

#ifndef MCAL_INTERRUPT_GEN_CFG_H
#define	MCAL_INTERRUPT_GEN_CFG_H

#define INTERRUPT_ENABLE_FEATURE    1
#define INTERRUPT_DISABLE_FEATURE   0 

#define INTERRUPT_PRIORITY_FEATURE  INTERRUPT_DISABLE_FEATURE
#define INTERRUPT_INTx_FEATURE      INTERRUPT_ENABLE_FEATURE
#define INTERRUPT_ON_CHANGE_FEATURE INTERRUPT_ENABLE_FEATURE




#endif	/* MCAL_INTERRUPT_GEN_CFG_H */

